# Generated by Django 5.1.6 on 2025-02-17 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=3, unique=True)),
                ('brand', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.CharField(max_length=30)),
                ('mouth_size', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('current_quantity', models.PositiveIntegerField()),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier')),
            ],
        ),
    ]
